
---
apiVersion: v1
kind: Namespace
metadata:
  name: billing-build
  labels:
    app : billing
    team: acme-corp
    build-namespace: billing-build
    environment: build
    argocd.argoproj.io/managed-by: billing-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: billing-dev
  labels:
    app : billing
    team: acme-corp
    build-namespace: billing-build
    environment: dev
    argocd.argoproj.io/managed-by: billing-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: billing-test
  labels:
    app : billing
    team: acme-corp
    build-namespace: billing-build
    environment: test
    argocd.argoproj.io/managed-by: billing-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: billing-prod
  labels:
    app : billing
    team: acme-corp
    build-namespace: billing-build
    environment: prod
    argocd.argoproj.io/managed-by: billing-build
